add support for ip route

diff --git a/bin/add-route b/bin/add-route
--- a/bin/add-route
+++ b/bin/add-route
@@ -6,5 +6,12 @@ if [ `uname` = "Darwin" ]; then
   sudo route delete -net 10.244.0.0/19 192.168.50.4 > /dev/null 2>&1
   sudo route add -net 10.244.0.0/19 192.168.50.4
 elif [ `uname` = "Linux" ]; then
-  sudo route add -net 10.244.0.0/19 gw 192.168.50.4
+  if type route > /dev/null; then
+    sudo route add -net 10.244.0.0/19 gw 192.168.50.4
+  elif type ip > /dev/null; then
+    sudo ip route add 10.244.0.0/19 via 192.168.50.4
+  else
+    echo "ERROR adding route"
+    exit 1
+  fi
 fi
